services:
  - type: web
    name: novacare-disease-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    rootDir: ./Dataset
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO

  - type: web
    name: novacare-hospital-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    rootDir: ./hospital_referal
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO
